### ISSUE TITLE
Send active instrument in context

### ISSUE THREAD

**Issue by celian-garcia** [milobella/device#45]
Purpose of this is mainly to know which instrument needs to be played/paused, but it can be useful in the future to send some state information about the device. 

So the model could be : 

```yaml
device:
  instruments:
  - kind: "chromecast"
    actions: ["play", "pause", "play_media"]
    name: "salon"
    state:
      status: "active" # or something more accurate, to be thought
      last_action:  # eventually last action executed on this instrument
        identifier: "play_media"
        params: ....
```
